### Create Product
PUT http://localhost:8080/products/productId
content-type: application/json

{
    "name": "TV",
    "category": "Electronics",
    "sku": "productId",
    "price": 1.0,
    "stock": 10
}

### Get Product
GET http://localhost:8080/products/productId

### Search Products
GET http://localhost:8080/products/?search=lavarropas

### Add Image to Product
POST http://localhost:8080/products/productId/images
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="image.jpg"
Content-Type: image/jpeg

< ./image.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--