version: "3.1"

services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=dynamodb,s3
      - DATA_DIR=/tmp/localstack/data
    ports:
      - "4566-4583:4566-4583"
    volumes:
      - "localstack-vol:/tmp/localstack"
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=user
      - POSTGRES_DB=antilope
    ports:
      - 5432:5432
volumes:
  localstack-vol: #//d/Misc/Containers/Antilope
