export enum PurchaseStatus {
  CREATED = "CREATED",
  WAITING_PAYMENT = "WAITING_PAYMENT",
  COMPLETED = "COMPLETED",
  DOCUMENTED = "DOCUMENTED",
  PAYMENT_REJECTED = "PAYMENT_REJECTED",
  CANCELLED = "CANCELLED",
}
