### Create Product
PUT http://localhost:3000/products/productId
content-type: application/json

{
    "Name": "TV",
    "Category": "Electronics",
    "Sku": "productId",
    "Price": 100.05,
    "Stock": 10
}

### Get Product
GET http://localhost:3000/products/productId

### Search Products
GET http://localhost:3000/products/

### Add Image to Product
POST http://localhost:3000/products/productId/images
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="image.jpg"
Content-Type: image/jpeg

< ./image.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--