### Create Product
PUT http://localhost:3000/products/123
content-type: application/json

{
    "Name": "TV",
    "Category": "Electronics",
    "Sku": "123"
}

### Get Product
GET http://localhost:3000/products/123

### Search Products
GET http://localhost:3000/products/

### Add Image to Product
POST http://localhost:3000/products/123/images
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="image.jpg"
Content-Type: image/jpeg

< ./image.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--